# Generated by Django 5.0.7 on 2025-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='English', max_length=50)),
                ('page_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
