# Generated by Django 5.0.7 on 2025-02-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='booksimg/'),
        ),
    ]
